# Generated by Django 3.1 on 2021-03-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210303_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=64)),
                ('auctionid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
