# Generated by Django 3.1 on 2021-03-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210304_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auctionid',
            field=models.IntegerField(default=None),
        ),
    ]
