# Generated by Django 3.1 on 2021-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid_auctionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
