# Generated by Django 3.1 on 2021-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlist_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
