# Generated by Django 3.1 on 2021-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210306_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='winneruser',
            field=models.CharField(default='', max_length=64),
        ),
    ]
