# Generated by Django 3.1 on 2021-03-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210307_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auctionid',
            field=models.IntegerField(default=None),
        ),
    ]
