# Generated by Django 3.1 on 2021-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_comment_auctionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.CharField(default='', max_length=64),
        ),
    ]
