# Generated by Django 3.1 on 2021-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210309_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='img',
            field=models.URLField(default=None, null=True),
        ),
    ]
