# Generated by Django 3.1 on 2021-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210326_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='img',
            field=models.URLField(blank=True, default=None),
        ),
    ]
